; Listing generated by Microsoft (R) Optimizing Compiler Version 19.13.26131.1 

	TITLE	C:\Users\smith\Projects\CallCenter\TBinaryData.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

PUBLIC	?__empty_global_delete@@YAXPAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPAXI@Z		; __empty_global_delete
PUBLIC	??0?$__TBD_TMemory@$0CAA@@@IAE@XZ		; __TBD_TMemory<512>::__TBD_TMemory<512>
PUBLIC	??1?$__TBD_TMemory@$0CAA@@@MAE@XZ		; __TBD_TMemory<512>::~__TBD_TMemory<512>
PUBLIC	?Reset@?$__TBD_TMemory@$0CAA@@@IAEXXZ		; __TBD_TMemory<512>::Reset
PUBLIC	?SetSize@?$__TBD_TMemory@$0CAA@@@IAEXI@Z	; __TBD_TMemory<512>::SetSize
PUBLIC	?AppendBytes@?$__TBD_TMemory@$0CAA@@@IAEXPAXI@Z	; __TBD_TMemory<512>::AppendBytes
PUBLIC	??_G?$__TBD_TMemory@$0CAA@@@MAEPAXI@Z		; __TBD_TMemory<512>::`scalar deleting destructor'
PUBLIC	??0TBinaryData@@QAE@XZ				; TBinaryData::TBinaryData
PUBLIC	??0TBinaryData@@QAE@ABV0@@Z			; TBinaryData::TBinaryData
PUBLIC	??0TBinaryData@@QAE@PAXI@Z			; TBinaryData::TBinaryData
PUBLIC	??1TBinaryData@@UAE@XZ				; TBinaryData::~TBinaryData
PUBLIC	?GetSizeForStore@TBinaryData@@QBEIXZ		; TBinaryData::GetSizeForStore
PUBLIC	?GetSize@TBinaryData@@QBEIXZ			; TBinaryData::GetSize
PUBLIC	?Reset@TBinaryData@@QAEXXZ			; TBinaryData::Reset
PUBLIC	?GetAdjustedPtr@TBinaryData@@QAEPAXI@Z		; TBinaryData::GetAdjustedPtr
PUBLIC	?SetSize@TBinaryData@@QAE_NI@Z			; TBinaryData::SetSize
PUBLIC	?LoadFrom@TBinaryData@@QAE_NPAX@Z		; TBinaryData::LoadFrom
PUBLIC	?SaveTo@TBinaryData@@QAE_NPAX@Z			; TBinaryData::SaveTo
PUBLIC	?WriteDataFrom@TBinaryData@@QAEXPAXI@Z		; TBinaryData::WriteDataFrom
PUBLIC	?ReadDataTo@TBinaryData@@QAEXPAXI@Z		; TBinaryData::ReadDataTo
PUBLIC	?LoadDataFrom@TBinaryData@@QAE_NPAXI@Z		; TBinaryData::LoadDataFrom
PUBLIC	?SaveDataTo@TBinaryData@@QAE_NPAXI@Z		; TBinaryData::SaveDataTo
PUBLIC	??6TBinaryData@@QAEAAV0@AB_N@Z			; TBinaryData::operator<<
PUBLIC	??6TBinaryData@@QAEAAV0@ABD@Z			; TBinaryData::operator<<
PUBLIC	??6TBinaryData@@QAEAAV0@ABE@Z			; TBinaryData::operator<<
PUBLIC	??6TBinaryData@@QAEAAV0@ABH@Z			; TBinaryData::operator<<
PUBLIC	??6TBinaryData@@QAEAAV0@ABI@Z			; TBinaryData::operator<<
PUBLIC	??6TBinaryData@@QAEAAV0@ABJ@Z			; TBinaryData::operator<<
PUBLIC	??6TBinaryData@@QAEAAV0@ABK@Z			; TBinaryData::operator<<
PUBLIC	??6TBinaryData@@QAEAAV0@ABV0@@Z			; TBinaryData::operator<<
PUBLIC	??5TBinaryData@@QAEAAV0@AA_N@Z			; TBinaryData::operator>>
PUBLIC	??5TBinaryData@@QAEAAV0@AAD@Z			; TBinaryData::operator>>
PUBLIC	??5TBinaryData@@QAEAAV0@AAE@Z			; TBinaryData::operator>>
PUBLIC	??5TBinaryData@@QAEAAV0@AAH@Z			; TBinaryData::operator>>
PUBLIC	??5TBinaryData@@QAEAAV0@AAI@Z			; TBinaryData::operator>>
PUBLIC	??5TBinaryData@@QAEAAV0@AAJ@Z			; TBinaryData::operator>>
PUBLIC	??5TBinaryData@@QAEAAV0@AAK@Z			; TBinaryData::operator>>
PUBLIC	??5TBinaryData@@QAEAAV0@AAV0@@Z			; TBinaryData::operator>>
PUBLIC	?__writefrom@TBinaryData@@AAEXPAXI@Z		; TBinaryData::__writefrom
PUBLIC	?__readto@TBinaryData@@AAEXPAXI@Z		; TBinaryData::__readto
PUBLIC	??_GTBinaryData@@UAEPAXI@Z			; TBinaryData::`scalar deleting destructor'
PUBLIC	??_7?$__TBD_TMemory@$0CAA@@@6B@			; __TBD_TMemory<512>::`vftable'
PUBLIC	??_7TBinaryData@@6B@				; TBinaryData::`vftable'
PUBLIC	__TI1?AVNoDataForRead@TBinaryData@@
PUBLIC	__CTA1?AVNoDataForRead@TBinaryData@@
PUBLIC	??_R0?AVNoDataForRead@TBinaryData@@@8		; TBinaryData::NoDataForRead `RTTI Type Descriptor'
PUBLIC	__CT??_R0?AVNoDataForRead@TBinaryData@@@81
PUBLIC	??_R4?$__TBD_TMemory@$0CAA@@@6B@		; __TBD_TMemory<512>::`RTTI Complete Object Locator'
PUBLIC	??_R0?AV?$__TBD_TMemory@$0CAA@@@@8		; __TBD_TMemory<512> `RTTI Type Descriptor'
PUBLIC	??_R3?$__TBD_TMemory@$0CAA@@@8			; __TBD_TMemory<512>::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2?$__TBD_TMemory@$0CAA@@@8			; __TBD_TMemory<512>::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@?$__TBD_TMemory@$0CAA@@@8		; __TBD_TMemory<512>::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R4TBinaryData@@6B@				; TBinaryData::`RTTI Complete Object Locator'
PUBLIC	??_R0?AVTBinaryData@@@8				; TBinaryData `RTTI Type Descriptor'
PUBLIC	??_R3TBinaryData@@8				; TBinaryData::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2TBinaryData@@8				; TBinaryData::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@TBinaryData@@8			; TBinaryData::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R1A@?0A@EN@?$__TBD_TMemory@$0CAA@@@8		; __TBD_TMemory<512>::`RTTI Base Class Descriptor at (0,-1,0,77)'
EXTRN	??3@YAXPAXI@Z:PROC				; operator delete
EXTRN	??_U@YAPAXI@Z:PROC				; operator new[]
EXTRN	??_V@YAXPAX@Z:PROC				; operator delete[]
EXTRN	_memcpy:PROC
EXTRN	__imp__ReadFile@20:PROC
EXTRN	__imp__WriteFile@20:PROC
EXTRN	??_E?$__TBD_TMemory@$0CAA@@@MAEPAXI@Z:PROC	; __TBD_TMemory<512>::`vector deleting destructor'
EXTRN	??_ETBinaryData@@UAEPAXI@Z:PROC			; TBinaryData::`vector deleting destructor'
EXTRN	@_RTC_CheckStackVars@8:PROC
EXTRN	@__security_check_cookie@4:PROC
EXTRN	__CxxThrowException@8:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	___CxxFrameHandler3:PROC
EXTRN	??_7type_info@@6B@:QWORD			; type_info::`vftable'
EXTRN	___security_cookie:DWORD
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
;	COMDAT ??_R1A@?0A@EN@?$__TBD_TMemory@$0CAA@@@8
rdata$r	SEGMENT
??_R1A@?0A@EN@?$__TBD_TMemory@$0CAA@@@8 DD FLAT:??_R0?AV?$__TBD_TMemory@$0CAA@@@@8 ; __TBD_TMemory<512>::`RTTI Base Class Descriptor at (0,-1,0,77)'
	DD	00H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	04dH
	DD	FLAT:??_R3?$__TBD_TMemory@$0CAA@@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@TBinaryData@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@TBinaryData@@8 DD FLAT:??_R0?AVTBinaryData@@@8 ; TBinaryData::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	01H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3TBinaryData@@8
rdata$r	ENDS
;	COMDAT ??_R2TBinaryData@@8
rdata$r	SEGMENT
??_R2TBinaryData@@8 DD FLAT:??_R1A@?0A@EA@TBinaryData@@8 ; TBinaryData::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EN@?$__TBD_TMemory@$0CAA@@@8
rdata$r	ENDS
;	COMDAT ??_R3TBinaryData@@8
rdata$r	SEGMENT
??_R3TBinaryData@@8 DD 00H				; TBinaryData::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	02H
	DD	FLAT:??_R2TBinaryData@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVTBinaryData@@@8
data$r	SEGMENT
??_R0?AVTBinaryData@@@8 DD FLAT:??_7type_info@@6B@	; TBinaryData `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVTBinaryData@@', 00H
data$r	ENDS
;	COMDAT ??_R4TBinaryData@@6B@
rdata$r	SEGMENT
??_R4TBinaryData@@6B@ DD 00H				; TBinaryData::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	FLAT:??_R0?AVTBinaryData@@@8
	DD	FLAT:??_R3TBinaryData@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@?$__TBD_TMemory@$0CAA@@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@?$__TBD_TMemory@$0CAA@@@8 DD FLAT:??_R0?AV?$__TBD_TMemory@$0CAA@@@@8 ; __TBD_TMemory<512>::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	00H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3?$__TBD_TMemory@$0CAA@@@8
rdata$r	ENDS
;	COMDAT ??_R2?$__TBD_TMemory@$0CAA@@@8
rdata$r	SEGMENT
??_R2?$__TBD_TMemory@$0CAA@@@8 DD FLAT:??_R1A@?0A@EA@?$__TBD_TMemory@$0CAA@@@8 ; __TBD_TMemory<512>::`RTTI Base Class Array'
rdata$r	ENDS
;	COMDAT ??_R3?$__TBD_TMemory@$0CAA@@@8
rdata$r	SEGMENT
??_R3?$__TBD_TMemory@$0CAA@@@8 DD 00H			; __TBD_TMemory<512>::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	01H
	DD	FLAT:??_R2?$__TBD_TMemory@$0CAA@@@8
rdata$r	ENDS
;	COMDAT ??_R0?AV?$__TBD_TMemory@$0CAA@@@@8
data$r	SEGMENT
??_R0?AV?$__TBD_TMemory@$0CAA@@@@8 DD FLAT:??_7type_info@@6B@ ; __TBD_TMemory<512> `RTTI Type Descriptor'
	DD	00H
	DB	'.?AV?$__TBD_TMemory@$0CAA@@@', 00H
data$r	ENDS
;	COMDAT ??_R4?$__TBD_TMemory@$0CAA@@@6B@
rdata$r	SEGMENT
??_R4?$__TBD_TMemory@$0CAA@@@6B@ DD 00H			; __TBD_TMemory<512>::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	FLAT:??_R0?AV?$__TBD_TMemory@$0CAA@@@@8
	DD	FLAT:??_R3?$__TBD_TMemory@$0CAA@@@8
rdata$r	ENDS
;	COMDAT __CT??_R0?AVNoDataForRead@TBinaryData@@@81
xdata$x	SEGMENT
__CT??_R0?AVNoDataForRead@TBinaryData@@@81 DD 00H
	DD	FLAT:??_R0?AVNoDataForRead@TBinaryData@@@8
	DD	00H
	DD	0ffffffffH
	ORG $+4
	DD	01H
	DD	00H
xdata$x	ENDS
;	COMDAT ??_R0?AVNoDataForRead@TBinaryData@@@8
data$r	SEGMENT
??_R0?AVNoDataForRead@TBinaryData@@@8 DD FLAT:??_7type_info@@6B@ ; TBinaryData::NoDataForRead `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVNoDataForRead@TBinaryData@@', 00H
data$r	ENDS
;	COMDAT __CTA1?AVNoDataForRead@TBinaryData@@
xdata$x	SEGMENT
__CTA1?AVNoDataForRead@TBinaryData@@ DD 01H
	DD	FLAT:__CT??_R0?AVNoDataForRead@TBinaryData@@@81
xdata$x	ENDS
;	COMDAT __TI1?AVNoDataForRead@TBinaryData@@
xdata$x	SEGMENT
__TI1?AVNoDataForRead@TBinaryData@@ DD 00H
	DD	00H
	DD	00H
	DD	FLAT:__CTA1?AVNoDataForRead@TBinaryData@@
xdata$x	ENDS
;	COMDAT ??_7TBinaryData@@6B@
CONST	SEGMENT
??_7TBinaryData@@6B@ DD FLAT:??_R4TBinaryData@@6B@	; TBinaryData::`vftable'
	DD	FLAT:??_ETBinaryData@@UAEPAXI@Z
CONST	ENDS
;	COMDAT ??_7?$__TBD_TMemory@$0CAA@@@6B@
CONST	SEGMENT
??_7?$__TBD_TMemory@$0CAA@@@6B@ DD FLAT:??_R4?$__TBD_TMemory@$0CAA@@@6B@ ; __TBD_TMemory<512>::`vftable'
	DD	FLAT:??_E?$__TBD_TMemory@$0CAA@@@MAEPAXI@Z
CONST	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__unwindtable$??0TBinaryData@@QAE@PAXI@Z DD 0ffffffffH
	DD	FLAT:__unwindfunclet$??0TBinaryData@@QAE@PAXI@Z$0
__ehfuncinfo$??0TBinaryData@@QAE@PAXI@Z DD 019930522H
	DD	01H
	DD	FLAT:__unwindtable$??0TBinaryData@@QAE@PAXI@Z
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	01H
xdata$x	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__unwindtable$??0TBinaryData@@QAE@ABV0@@Z DD 0ffffffffH
	DD	FLAT:__unwindfunclet$??0TBinaryData@@QAE@ABV0@@Z$0
__ehfuncinfo$??0TBinaryData@@QAE@ABV0@@Z DD 019930522H
	DD	01H
	DD	FLAT:__unwindtable$??0TBinaryData@@QAE@ABV0@@Z
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	01H
xdata$x	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??_GTBinaryData@@UAEPAXI@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
___flags$ = 8						; size = 4
??_GTBinaryData@@UAEPAXI@Z PROC				; TBinaryData::`scalar deleting destructor', COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	??1TBinaryData@@UAE@XZ			; TBinaryData::~TBinaryData
	mov	eax, DWORD PTR ___flags$[ebp]
	and	eax, 1
	je	SHORT $LN2@scalar
	push	20					; 00000014H
	mov	eax, DWORD PTR _this$[ebp]
	push	eax
	call	??3@YAXPAXI@Z				; operator delete
	add	esp, 8
$LN2@scalar:
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??_GTBinaryData@@UAEPAXI@Z ENDP				; TBinaryData::`scalar deleting destructor'
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ?__readto@TBinaryData@@AAEXPAXI@Z
_TEXT	SEGMENT
$T1 = -209						; size = 1
_this$ = -8						; size = 4
_ptr$ = 8						; size = 4
_sz$ = 12						; size = 4
?__readto@TBinaryData@@AAEXPAXI@Z PROC			; TBinaryData::__readto, COMDAT
; _this$ = ecx

; 74   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 216				; 000000d8H
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-216]
	mov	ecx, 54					; 00000036H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 75   : 	if (CurPosForReading-__TBD_TBlockedMemory::data+sz > size)

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [eax+16]
	sub	edx, DWORD PTR [ecx+4]
	add	edx, DWORD PTR _sz$[ebp]
	mov	eax, DWORD PTR _this$[ebp]
	cmp	edx, DWORD PTR [eax+8]
	jbe	SHORT $LN2@readto

; 76   : 		throw NoDataForRead();

	push	OFFSET __TI1?AVNoDataForRead@TBinaryData@@
	lea	eax, DWORD PTR $T1[ebp]
	push	eax
	call	__CxxThrowException@8
$LN2@readto:

; 77   : 	memcpy(ptr, CurPosForReading, sz);

	mov	eax, DWORD PTR _sz$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [ecx+16]
	push	edx
	mov	eax, DWORD PTR _ptr$[ebp]
	push	eax
	call	_memcpy
	add	esp, 12					; 0000000cH

; 78   : 	CurPosForReading += sz;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+16]
	add	ecx, DWORD PTR _sz$[ebp]
	mov	edx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [edx+16], ecx
$LN3@readto:

; 79   : }

	pop	edi
	pop	esi
	pop	ebx
	add	esp, 216				; 000000d8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	8
?__readto@TBinaryData@@AAEXPAXI@Z ENDP			; TBinaryData::__readto
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ?__writefrom@TBinaryData@@AAEXPAXI@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_ptr$ = 8						; size = 4
_sz$ = 12						; size = 4
?__writefrom@TBinaryData@@AAEXPAXI@Z PROC		; TBinaryData::__writefrom, COMDAT
; _this$ = ecx

; 67   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 68   : 	CurPosForReading = CurPosForReading - (int)__TBD_TBlockedMemory::data; 

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [eax+16]
	sub	edx, DWORD PTR [ecx+4]
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax+16], edx

; 69   : 	AppendBytes(ptr, sz);

	mov	eax, DWORD PTR _sz$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ptr$[ebp]
	push	ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	?AppendBytes@?$__TBD_TMemory@$0CAA@@@IAEXPAXI@Z ; __TBD_TMemory<512>::AppendBytes

; 70   : 	CurPosForReading = CurPosForReading + (int)__TBD_TBlockedMemory::data;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+16]
	mov	edx, DWORD PTR _this$[ebp]
	add	ecx, DWORD PTR [edx+4]
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax+16], ecx

; 71   : }

	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	8
?__writefrom@TBinaryData@@AAEXPAXI@Z ENDP		; TBinaryData::__writefrom
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ??5TBinaryData@@QAEAAV0@AAV0@@Z
_TEXT	SEGMENT
_size$ = -20						; size = 4
_this$ = -8						; size = 4
_Value$ = 8						; size = 4
??5TBinaryData@@QAEAAV0@AAV0@@Z PROC			; TBinaryData::operator>>, COMDAT
; _this$ = ecx

; 204  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 216				; 000000d8H
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-216]
	mov	ecx, 54					; 00000036H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 205  : unsigned __int32 size;
; 206  : 	__readto((void *)&size, sizeof(size));

	push	4
	lea	eax, DWORD PTR _size$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?__readto@TBinaryData@@AAEXPAXI@Z	; TBinaryData::__readto

; 207  : 	Value.__TBD_TBlockedMemory::SetSize(size);

	mov	eax, DWORD PTR _size$[ebp]
	push	eax
	mov	ecx, DWORD PTR _Value$[ebp]
	call	?SetSize@?$__TBD_TMemory@$0CAA@@@IAEXI@Z ; __TBD_TMemory<512>::SetSize

; 208  : 	__readto(Value.data, size);

	mov	eax, DWORD PTR _size$[ebp]
	push	eax
	mov	ecx, DWORD PTR _Value$[ebp]
	mov	edx, DWORD PTR [ecx+4]
	push	edx
	mov	ecx, DWORD PTR _this$[ebp]
	call	?__readto@TBinaryData@@AAEXPAXI@Z	; TBinaryData::__readto

; 209  : 	return (*this);

	mov	eax, DWORD PTR _this$[ebp]

; 210  : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN5@operator
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 216				; 000000d8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
	npad	2
$LN5@operator:
	DD	1
	DD	$LN4@operator
$LN4@operator:
	DD	-20					; ffffffecH
	DD	4
	DD	$LN3@operator
$LN3@operator:
	DB	115					; 00000073H
	DB	105					; 00000069H
	DB	122					; 0000007aH
	DB	101					; 00000065H
	DB	0
??5TBinaryData@@QAEAAV0@AAV0@@Z ENDP			; TBinaryData::operator>>
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ??5TBinaryData@@QAEAAV0@AAK@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_Value$ = 8						; size = 4
??5TBinaryData@@QAEAAV0@AAK@Z PROC			; TBinaryData::operator>>, COMDAT
; _this$ = ecx

; 177  : {	__readto((void *)&Value, sizeof(Value)); return (*this); }

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	push	4
	mov	eax, DWORD PTR _Value$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?__readto@TBinaryData@@AAEXPAXI@Z	; TBinaryData::__readto
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??5TBinaryData@@QAEAAV0@AAK@Z ENDP			; TBinaryData::operator>>
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ??5TBinaryData@@QAEAAV0@AAJ@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_Value$ = 8						; size = 4
??5TBinaryData@@QAEAAV0@AAJ@Z PROC			; TBinaryData::operator>>, COMDAT
; _this$ = ecx

; 174  : {	__readto((void *)&Value, sizeof(Value)); return (*this); }

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	push	4
	mov	eax, DWORD PTR _Value$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?__readto@TBinaryData@@AAEXPAXI@Z	; TBinaryData::__readto
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??5TBinaryData@@QAEAAV0@AAJ@Z ENDP			; TBinaryData::operator>>
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ??5TBinaryData@@QAEAAV0@AAI@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_Value$ = 8						; size = 4
??5TBinaryData@@QAEAAV0@AAI@Z PROC			; TBinaryData::operator>>, COMDAT
; _this$ = ecx

; 171  : {	__readto((void *)&Value, sizeof(Value)); return (*this); }

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	push	4
	mov	eax, DWORD PTR _Value$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?__readto@TBinaryData@@AAEXPAXI@Z	; TBinaryData::__readto
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??5TBinaryData@@QAEAAV0@AAI@Z ENDP			; TBinaryData::operator>>
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ??5TBinaryData@@QAEAAV0@AAH@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_Value$ = 8						; size = 4
??5TBinaryData@@QAEAAV0@AAH@Z PROC			; TBinaryData::operator>>, COMDAT
; _this$ = ecx

; 168  : {	__readto((void *)&Value, sizeof(Value)); return (*this); }

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	push	4
	mov	eax, DWORD PTR _Value$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?__readto@TBinaryData@@AAEXPAXI@Z	; TBinaryData::__readto
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??5TBinaryData@@QAEAAV0@AAH@Z ENDP			; TBinaryData::operator>>
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ??5TBinaryData@@QAEAAV0@AAE@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_Value$ = 8						; size = 4
??5TBinaryData@@QAEAAV0@AAE@Z PROC			; TBinaryData::operator>>, COMDAT
; _this$ = ecx

; 165  : {	__readto((void *)&Value, sizeof(Value)); return (*this); }

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	push	1
	mov	eax, DWORD PTR _Value$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?__readto@TBinaryData@@AAEXPAXI@Z	; TBinaryData::__readto
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??5TBinaryData@@QAEAAV0@AAE@Z ENDP			; TBinaryData::operator>>
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ??5TBinaryData@@QAEAAV0@AAD@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_Value$ = 8						; size = 4
??5TBinaryData@@QAEAAV0@AAD@Z PROC			; TBinaryData::operator>>, COMDAT
; _this$ = ecx

; 162  : {	__readto((void *)&Value, sizeof(Value)); return (*this); }

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	push	1
	mov	eax, DWORD PTR _Value$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?__readto@TBinaryData@@AAEXPAXI@Z	; TBinaryData::__readto
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??5TBinaryData@@QAEAAV0@AAD@Z ENDP			; TBinaryData::operator>>
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ??5TBinaryData@@QAEAAV0@AA_N@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_Value$ = 8						; size = 4
??5TBinaryData@@QAEAAV0@AA_N@Z PROC			; TBinaryData::operator>>, COMDAT
; _this$ = ecx

; 159  : {	__readto((void *)&Value, sizeof(Value)); return (*this); }

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	push	1
	mov	eax, DWORD PTR _Value$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?__readto@TBinaryData@@AAEXPAXI@Z	; TBinaryData::__readto
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??5TBinaryData@@QAEAAV0@AA_N@Z ENDP			; TBinaryData::operator>>
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ??6TBinaryData@@QAEAAV0@ABV0@@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_Value$ = 8						; size = 4
??6TBinaryData@@QAEAAV0@ABV0@@Z PROC			; TBinaryData::operator<<, COMDAT
; _this$ = ecx

; 151  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 152  : 	if (this==&Value) return (*this);

	mov	eax, DWORD PTR _this$[ebp]
	cmp	eax, DWORD PTR _Value$[ebp]
	jne	SHORT $LN2@operator
	mov	eax, DWORD PTR _this$[ebp]
	jmp	SHORT $LN1@operator
$LN2@operator:

; 153  : 	this->__writefrom((void *)&Value.size, sizeof(Value.size));

	push	4
	mov	eax, DWORD PTR _Value$[ebp]
	add	eax, 8
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?__writefrom@TBinaryData@@AAEXPAXI@Z	; TBinaryData::__writefrom

; 154  : 	__writefrom(Value.data, Value.size);

	mov	eax, DWORD PTR _Value$[ebp]
	mov	ecx, DWORD PTR [eax+8]
	push	ecx
	mov	edx, DWORD PTR _Value$[ebp]
	mov	eax, DWORD PTR [edx+4]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?__writefrom@TBinaryData@@AAEXPAXI@Z	; TBinaryData::__writefrom

; 155  : 	return (*this);

	mov	eax, DWORD PTR _this$[ebp]
$LN1@operator:

; 156  : }

	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??6TBinaryData@@QAEAAV0@ABV0@@Z ENDP			; TBinaryData::operator<<
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ??6TBinaryData@@QAEAAV0@ABK@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_Value$ = 8						; size = 4
??6TBinaryData@@QAEAAV0@ABK@Z PROC			; TBinaryData::operator<<, COMDAT
; _this$ = ecx

; 124  : {	__writefrom((void *)&Value, sizeof(Value));	return (*this); }

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	push	4
	mov	eax, DWORD PTR _Value$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?__writefrom@TBinaryData@@AAEXPAXI@Z	; TBinaryData::__writefrom
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??6TBinaryData@@QAEAAV0@ABK@Z ENDP			; TBinaryData::operator<<
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ??6TBinaryData@@QAEAAV0@ABJ@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_Value$ = 8						; size = 4
??6TBinaryData@@QAEAAV0@ABJ@Z PROC			; TBinaryData::operator<<, COMDAT
; _this$ = ecx

; 121  : {	__writefrom((void *)&Value, sizeof(Value));	return (*this); }

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	push	4
	mov	eax, DWORD PTR _Value$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?__writefrom@TBinaryData@@AAEXPAXI@Z	; TBinaryData::__writefrom
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??6TBinaryData@@QAEAAV0@ABJ@Z ENDP			; TBinaryData::operator<<
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ??6TBinaryData@@QAEAAV0@ABI@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_Value$ = 8						; size = 4
??6TBinaryData@@QAEAAV0@ABI@Z PROC			; TBinaryData::operator<<, COMDAT
; _this$ = ecx

; 118  : {	__writefrom((void *)&Value, sizeof(Value));	return (*this); }

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	push	4
	mov	eax, DWORD PTR _Value$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?__writefrom@TBinaryData@@AAEXPAXI@Z	; TBinaryData::__writefrom
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??6TBinaryData@@QAEAAV0@ABI@Z ENDP			; TBinaryData::operator<<
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ??6TBinaryData@@QAEAAV0@ABH@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_Value$ = 8						; size = 4
??6TBinaryData@@QAEAAV0@ABH@Z PROC			; TBinaryData::operator<<, COMDAT
; _this$ = ecx

; 115  : {	__writefrom((void *)&Value, sizeof(Value));	return (*this); }

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	push	4
	mov	eax, DWORD PTR _Value$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?__writefrom@TBinaryData@@AAEXPAXI@Z	; TBinaryData::__writefrom
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??6TBinaryData@@QAEAAV0@ABH@Z ENDP			; TBinaryData::operator<<
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ??6TBinaryData@@QAEAAV0@ABE@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_Value$ = 8						; size = 4
??6TBinaryData@@QAEAAV0@ABE@Z PROC			; TBinaryData::operator<<, COMDAT
; _this$ = ecx

; 112  : {	__writefrom((void *)&Value, sizeof(Value));	return (*this); }

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	push	1
	mov	eax, DWORD PTR _Value$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?__writefrom@TBinaryData@@AAEXPAXI@Z	; TBinaryData::__writefrom
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??6TBinaryData@@QAEAAV0@ABE@Z ENDP			; TBinaryData::operator<<
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ??6TBinaryData@@QAEAAV0@ABD@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_Value$ = 8						; size = 4
??6TBinaryData@@QAEAAV0@ABD@Z PROC			; TBinaryData::operator<<, COMDAT
; _this$ = ecx

; 109  : {	__writefrom((void *)&Value, sizeof(Value));	return (*this); }

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	push	1
	mov	eax, DWORD PTR _Value$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?__writefrom@TBinaryData@@AAEXPAXI@Z	; TBinaryData::__writefrom
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??6TBinaryData@@QAEAAV0@ABD@Z ENDP			; TBinaryData::operator<<
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ??6TBinaryData@@QAEAAV0@AB_N@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_Value$ = 8						; size = 4
??6TBinaryData@@QAEAAV0@AB_N@Z PROC			; TBinaryData::operator<<, COMDAT
; _this$ = ecx

; 106  : {	__writefrom((void *)&Value, sizeof(Value));	return (*this); }

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	push	1
	mov	eax, DWORD PTR _Value$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?__writefrom@TBinaryData@@AAEXPAXI@Z	; TBinaryData::__writefrom
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??6TBinaryData@@QAEAAV0@AB_N@Z ENDP			; TBinaryData::operator<<
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ?SaveDataTo@TBinaryData@@QAE_NPAXI@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_ptr$ = 8						; size = 4
_sz$ = 12						; size = 4
?SaveDataTo@TBinaryData@@QAE_NPAXI@Z PROC		; TBinaryData::SaveDataTo, COMDAT
; _this$ = ecx

; 99   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 100  : 	memcpy(ptr, __TBD_TBlockedMemory::data, sz);

	mov	eax, DWORD PTR _sz$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [ecx+4]
	push	edx
	mov	eax, DWORD PTR _ptr$[ebp]
	push	eax
	call	_memcpy
	add	esp, 12					; 0000000cH

; 101  : 	return true;

	mov	al, 1

; 102  : }

	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	8
?SaveDataTo@TBinaryData@@QAE_NPAXI@Z ENDP		; TBinaryData::SaveDataTo
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ?LoadDataFrom@TBinaryData@@QAE_NPAXI@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_ptr$ = 8						; size = 4
_sz$ = 12						; size = 4
?LoadDataFrom@TBinaryData@@QAE_NPAXI@Z PROC		; TBinaryData::LoadDataFrom, COMDAT
; _this$ = ecx

; 92   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 93   : 	SetSize(sz);

	mov	eax, DWORD PTR _sz$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?SetSize@TBinaryData@@QAE_NI@Z		; TBinaryData::SetSize

; 94   : 	memcpy(__TBD_TBlockedMemory::data, ptr, sz);

	mov	eax, DWORD PTR _sz$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ptr$[ebp]
	push	ecx
	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [edx+4]
	push	eax
	call	_memcpy
	add	esp, 12					; 0000000cH

; 95   : 	return true;

	mov	al, 1

; 96   : }

	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	8
?LoadDataFrom@TBinaryData@@QAE_NPAXI@Z ENDP		; TBinaryData::LoadDataFrom
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ?ReadDataTo@TBinaryData@@QAEXPAXI@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_ptr$ = 8						; size = 4
_sz$ = 12						; size = 4
?ReadDataTo@TBinaryData@@QAEXPAXI@Z PROC		; TBinaryData::ReadDataTo, COMDAT
; _this$ = ecx

; 87   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 88   : 	__readto(ptr, sz);

	mov	eax, DWORD PTR _sz$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ptr$[ebp]
	push	ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	?__readto@TBinaryData@@AAEXPAXI@Z	; TBinaryData::__readto

; 89   : }

	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	8
?ReadDataTo@TBinaryData@@QAEXPAXI@Z ENDP		; TBinaryData::ReadDataTo
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ?WriteDataFrom@TBinaryData@@QAEXPAXI@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_ptr$ = 8						; size = 4
_sz$ = 12						; size = 4
?WriteDataFrom@TBinaryData@@QAEXPAXI@Z PROC		; TBinaryData::WriteDataFrom, COMDAT
; _this$ = ecx

; 82   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 83   : 	__writefrom(ptr, sz);

	mov	eax, DWORD PTR _sz$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ptr$[ebp]
	push	ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	?__writefrom@TBinaryData@@AAEXPAXI@Z	; TBinaryData::__writefrom

; 84   : }

	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	8
?WriteDataFrom@TBinaryData@@QAEXPAXI@Z ENDP		; TBinaryData::WriteDataFrom
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ?SaveTo@TBinaryData@@QAE_NPAX@Z
_TEXT	SEGMENT
_cbread$ = -20						; size = 4
_this$ = -8						; size = 4
_hFile$ = 8						; size = 4
?SaveTo@TBinaryData@@QAE_NPAX@Z PROC			; TBinaryData::SaveTo, COMDAT
; _this$ = ecx

; 229  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 216				; 000000d8H
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-216]
	mov	ecx, 54					; 00000036H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 230  : DWORD cbread;
; 231  : 	if (!WriteFile(hFile, &size, sizeof(size), &cbread, NULL)) return false;

	mov	esi, esp
	push	0
	lea	eax, DWORD PTR _cbread$[ebp]
	push	eax
	push	4
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 8
	push	ecx
	mov	edx, DWORD PTR _hFile$[ebp]
	push	edx
	call	DWORD PTR __imp__WriteFile@20
	cmp	esi, esp
	call	__RTC_CheckEsp
	test	eax, eax
	jne	SHORT $LN2@SaveTo
	xor	al, al
	jmp	SHORT $LN1@SaveTo
$LN2@SaveTo:

; 232  : 	if (!WriteFile(hFile, __TBD_TBlockedMemory::data, size, &cbread, NULL)) return false;

	mov	esi, esp
	push	0
	lea	eax, DWORD PTR _cbread$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [ecx+8]
	push	edx
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+4]
	push	ecx
	mov	edx, DWORD PTR _hFile$[ebp]
	push	edx
	call	DWORD PTR __imp__WriteFile@20
	cmp	esi, esp
	call	__RTC_CheckEsp
	test	eax, eax
	jne	SHORT $LN3@SaveTo
	xor	al, al
	jmp	SHORT $LN1@SaveTo
$LN3@SaveTo:

; 233  : 	return true;

	mov	al, 1
$LN1@SaveTo:

; 234  : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN7@SaveTo
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 216				; 000000d8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
	npad	3
$LN7@SaveTo:
	DD	1
	DD	$LN6@SaveTo
$LN6@SaveTo:
	DD	-20					; ffffffecH
	DD	4
	DD	$LN5@SaveTo
$LN5@SaveTo:
	DB	99					; 00000063H
	DB	98					; 00000062H
	DB	114					; 00000072H
	DB	101					; 00000065H
	DB	97					; 00000061H
	DB	100					; 00000064H
	DB	0
?SaveTo@TBinaryData@@QAE_NPAX@Z ENDP			; TBinaryData::SaveTo
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ?LoadFrom@TBinaryData@@QAE_NPAX@Z
_TEXT	SEGMENT
$T1 = -245						; size = 1
$T2 = -233						; size = 1
_k$ = -32						; size = 4
_cbread$ = -20						; size = 4
_this$ = -8						; size = 4
_hFile$ = 8						; size = 4
?LoadFrom@TBinaryData@@QAE_NPAX@Z PROC			; TBinaryData::LoadFrom, COMDAT
; _this$ = ecx

; 215  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 252				; 000000fcH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-252]
	mov	ecx, 63					; 0000003fH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 216  : DWORD cbread;
; 217  : unsigned int k;
; 218  : 	ReadFile(hFile, &k, sizeof(k), &cbread, NULL);

	mov	esi, esp
	push	0
	lea	eax, DWORD PTR _cbread$[ebp]
	push	eax
	push	4
	lea	ecx, DWORD PTR _k$[ebp]
	push	ecx
	mov	edx, DWORD PTR _hFile$[ebp]
	push	edx
	call	DWORD PTR __imp__ReadFile@20
	cmp	esi, esp
	call	__RTC_CheckEsp

; 219  : 	if (cbread!=sizeof(k)) 

	cmp	DWORD PTR _cbread$[ebp], 4
	je	SHORT $LN2@LoadFrom

; 220  : 		throw TBinaryData::NoDataForRead();

	push	OFFSET __TI1?AVNoDataForRead@TBinaryData@@
	lea	eax, DWORD PTR $T2[ebp]
	push	eax
	call	__CxxThrowException@8
$LN2@LoadFrom:

; 221  : 	SetSize(k);

	mov	eax, DWORD PTR _k$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?SetSize@TBinaryData@@QAE_NI@Z		; TBinaryData::SetSize

; 222  : 	ReadFile(hFile, __TBD_TBlockedMemory::data, size, &cbread, NULL);

	mov	esi, esp
	push	0
	lea	eax, DWORD PTR _cbread$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [ecx+8]
	push	edx
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+4]
	push	ecx
	mov	edx, DWORD PTR _hFile$[ebp]
	push	edx
	call	DWORD PTR __imp__ReadFile@20
	cmp	esi, esp
	call	__RTC_CheckEsp

; 223  : 	if (cbread!=size) 

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR _cbread$[ebp]
	cmp	ecx, DWORD PTR [eax+8]
	je	SHORT $LN3@LoadFrom

; 224  : 		throw TBinaryData::NoDataForRead();

	push	OFFSET __TI1?AVNoDataForRead@TBinaryData@@
	lea	eax, DWORD PTR $T1[ebp]
	push	eax
	call	__CxxThrowException@8
$LN3@LoadFrom:

; 225  : 	return true;

	mov	al, 1
$LN4@LoadFrom:

; 226  : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN8@LoadFrom
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 252				; 000000fcH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
	npad	3
$LN8@LoadFrom:
	DD	2
	DD	$LN7@LoadFrom
$LN7@LoadFrom:
	DD	-20					; ffffffecH
	DD	4
	DD	$LN5@LoadFrom
	DD	-32					; ffffffe0H
	DD	4
	DD	$LN6@LoadFrom
$LN6@LoadFrom:
	DB	107					; 0000006bH
	DB	0
$LN5@LoadFrom:
	DB	99					; 00000063H
	DB	98					; 00000062H
	DB	114					; 00000072H
	DB	101					; 00000065H
	DB	97					; 00000061H
	DB	100					; 00000064H
	DB	0
?LoadFrom@TBinaryData@@QAE_NPAX@Z ENDP			; TBinaryData::LoadFrom
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ?SetSize@TBinaryData@@QAE_NI@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
__sz$ = 8						; size = 4
?SetSize@TBinaryData@@QAE_NI@Z PROC			; TBinaryData::SetSize, COMDAT
; _this$ = ecx

; 60   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 61   : 	__TBD_TBlockedMemory::SetSize(_sz);

	mov	eax, DWORD PTR __sz$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?SetSize@?$__TBD_TMemory@$0CAA@@@IAEXI@Z ; __TBD_TMemory<512>::SetSize

; 62   : 	CurPosForReading = __TBD_TBlockedMemory::data;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [ecx+4]
	mov	DWORD PTR [eax+16], edx

; 63   : 	return true;

	mov	al, 1

; 64   : }

	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
?SetSize@TBinaryData@@QAE_NI@Z ENDP			; TBinaryData::SetSize
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ?GetAdjustedPtr@TBinaryData@@QAEPAXI@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_Offset$ = 8						; size = 4
?GetAdjustedPtr@TBinaryData@@QAEPAXI@Z PROC		; TBinaryData::GetAdjustedPtr, COMDAT
; _this$ = ecx

; 55   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 56   : 	return __TBD_TBlockedMemory::data+Offset;

	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+4]
	add	eax, DWORD PTR _Offset$[ebp]

; 57   : }

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	4
?GetAdjustedPtr@TBinaryData@@QAEPAXI@Z ENDP		; TBinaryData::GetAdjustedPtr
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ?Reset@TBinaryData@@QAEXXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?Reset@TBinaryData@@QAEXXZ PROC				; TBinaryData::Reset, COMDAT
; _this$ = ecx

; 49   : {	

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 50   : 	__TBD_TBlockedMemory::Reset();

	mov	ecx, DWORD PTR _this$[ebp]
	call	?Reset@?$__TBD_TMemory@$0CAA@@@IAEXXZ	; __TBD_TMemory<512>::Reset

; 51   : 	CurPosForReading = NULL; 

	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax+16], 0

; 52   : }

	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?Reset@TBinaryData@@QAEXXZ ENDP				; TBinaryData::Reset
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ?GetSize@TBinaryData@@QBEIXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?GetSize@TBinaryData@@QBEIXZ PROC			; TBinaryData::GetSize, COMDAT
; _this$ = ecx

; 44   : {	

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 45   : 	return size;

	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+8]

; 46   : }

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?GetSize@TBinaryData@@QBEIXZ ENDP			; TBinaryData::GetSize
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ?GetSizeForStore@TBinaryData@@QBEIXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?GetSizeForStore@TBinaryData@@QBEIXZ PROC		; TBinaryData::GetSizeForStore, COMDAT
; _this$ = ecx

; 39   : {	

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 40   : 	return size+sizeof(size);

	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+8]
	add	eax, 4

; 41   : }

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?GetSizeForStore@TBinaryData@@QBEIXZ ENDP		; TBinaryData::GetSizeForStore
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ??1TBinaryData@@UAE@XZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
??1TBinaryData@@UAE@XZ PROC				; TBinaryData::~TBinaryData, COMDAT
; _this$ = ecx

; 34   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], OFFSET ??_7TBinaryData@@6B@

; 35   : }

	mov	ecx, DWORD PTR _this$[ebp]
	call	??1?$__TBD_TMemory@$0CAA@@@MAE@XZ	; __TBD_TMemory<512>::~__TBD_TMemory<512>
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
??1TBinaryData@@UAE@XZ ENDP				; TBinaryData::~TBinaryData
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ??0TBinaryData@@QAE@PAXI@Z
_TEXT	SEGMENT
_this$ = -20						; size = 4
__$EHRec$ = -12						; size = 12
_ptr$ = 8						; size = 4
_sz$ = 12						; size = 4
??0TBinaryData@@QAE@PAXI@Z PROC				; TBinaryData::TBinaryData, COMDAT
; _this$ = ecx

; 27   : {

	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$??0TBinaryData@@QAE@PAXI@Z
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-216]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
	mov	DWORD PTR _this$[ebp], ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	??0?$__TBD_TMemory@$0CAA@@@IAE@XZ	; __TBD_TMemory<512>::__TBD_TMemory<512>
	mov	DWORD PTR __$EHRec$[ebp+8], 0
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], OFFSET ??_7TBinaryData@@6B@

; 28   : 	__TBD_TBlockedMemory::SetSize(sz);

	mov	eax, DWORD PTR _sz$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?SetSize@?$__TBD_TMemory@$0CAA@@@IAEXI@Z ; __TBD_TMemory<512>::SetSize

; 29   : 	memcpy(data, ptr, sz);

	mov	eax, DWORD PTR _sz$[ebp]
	push	eax
	mov	ecx, DWORD PTR _ptr$[ebp]
	push	ecx
	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [edx+4]
	push	eax
	call	_memcpy
	add	esp, 12					; 0000000cH

; 30   : 	CurPosForReading = this->data;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [ecx+4]
	mov	DWORD PTR [eax+16], edx

; 31   : }

	mov	DWORD PTR __$EHRec$[ebp+8], -1
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 216				; 000000d8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	8
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__unwindfunclet$??0TBinaryData@@QAE@PAXI@Z$0:
	mov	ecx, DWORD PTR _this$[ebp]
	jmp	??1?$__TBD_TMemory@$0CAA@@@MAE@XZ	; __TBD_TMemory<512>::~__TBD_TMemory<512>
__ehhandler$??0TBinaryData@@QAE@PAXI@Z:
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-220]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$??0TBinaryData@@QAE@PAXI@Z
	jmp	___CxxFrameHandler3
text$x	ENDS
??0TBinaryData@@QAE@PAXI@Z ENDP				; TBinaryData::TBinaryData
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ??0TBinaryData@@QAE@ABV0@@Z
_TEXT	SEGMENT
_this$ = -20						; size = 4
__$EHRec$ = -12						; size = 12
_A$ = 8							; size = 4
??0TBinaryData@@QAE@ABV0@@Z PROC			; TBinaryData::TBinaryData, COMDAT
; _this$ = ecx

; 20   : {

	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$??0TBinaryData@@QAE@ABV0@@Z
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-216]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
	mov	DWORD PTR _this$[ebp], ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	??0?$__TBD_TMemory@$0CAA@@@IAE@XZ	; __TBD_TMemory<512>::__TBD_TMemory<512>
	mov	DWORD PTR __$EHRec$[ebp+8], 0
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], OFFSET ??_7TBinaryData@@6B@

; 21   : 	__TBD_TBlockedMemory::SetSize(A.size);

	mov	eax, DWORD PTR _A$[ebp]
	mov	ecx, DWORD PTR [eax+8]
	push	ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	?SetSize@?$__TBD_TMemory@$0CAA@@@IAEXI@Z ; __TBD_TMemory<512>::SetSize

; 22   : 	memcpy(data, A.data, size);

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+8]
	push	ecx
	mov	edx, DWORD PTR _A$[ebp]
	mov	eax, DWORD PTR [edx+4]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [ecx+4]
	push	edx
	call	_memcpy
	add	esp, 12					; 0000000cH

; 23   : 	CurPosForReading = this->data;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [ecx+4]
	mov	DWORD PTR [eax+16], edx

; 24   : }

	mov	DWORD PTR __$EHRec$[ebp+8], -1
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 216				; 000000d8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__unwindfunclet$??0TBinaryData@@QAE@ABV0@@Z$0:
	mov	ecx, DWORD PTR _this$[ebp]
	jmp	??1?$__TBD_TMemory@$0CAA@@@MAE@XZ	; __TBD_TMemory<512>::~__TBD_TMemory<512>
__ehhandler$??0TBinaryData@@QAE@ABV0@@Z:
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-220]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$??0TBinaryData@@QAE@ABV0@@Z
	jmp	___CxxFrameHandler3
text$x	ENDS
??0TBinaryData@@QAE@ABV0@@Z ENDP			; TBinaryData::TBinaryData
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ??0TBinaryData@@QAE@XZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
??0TBinaryData@@QAE@XZ PROC				; TBinaryData::TBinaryData, COMDAT
; _this$ = ecx

; 15   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	??0?$__TBD_TMemory@$0CAA@@@IAE@XZ	; __TBD_TMemory<512>::__TBD_TMemory<512>
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], OFFSET ??_7TBinaryData@@6B@

; 16   : 	CurPosForReading = this->data;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [ecx+4]
	mov	DWORD PTR [eax+16], edx

; 17   : }

	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
??0TBinaryData@@QAE@XZ ENDP				; TBinaryData::TBinaryData
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??_G?$__TBD_TMemory@$0CAA@@@MAEPAXI@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
___flags$ = 8						; size = 4
??_G?$__TBD_TMemory@$0CAA@@@MAEPAXI@Z PROC		; __TBD_TMemory<512>::`scalar deleting destructor', COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	??1?$__TBD_TMemory@$0CAA@@@MAE@XZ	; __TBD_TMemory<512>::~__TBD_TMemory<512>
	mov	eax, DWORD PTR ___flags$[ebp]
	and	eax, 1
	je	SHORT $LN2@scalar
	push	16					; 00000010H
	mov	eax, DWORD PTR _this$[ebp]
	push	eax
	call	??3@YAXPAXI@Z				; operator delete
	add	esp, 8
$LN2@scalar:
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??_G?$__TBD_TMemory@$0CAA@@@MAEPAXI@Z ENDP		; __TBD_TMemory<512>::`scalar deleting destructor'
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.h
;	COMDAT ?AppendBytes@?$__TBD_TMemory@$0CAA@@@IAEXPAXI@Z
_TEXT	SEGMENT
tv76 = -244						; size = 4
$T1 = -236						; size = 4
$T2 = -224						; size = 4
_OldData$3 = -20					; size = 4
_this$ = -8						; size = 4
_mem$ = 8						; size = 4
_sz$ = 12						; size = 4
?AppendBytes@?$__TBD_TMemory@$0CAA@@@IAEXPAXI@Z PROC	; __TBD_TMemory<512>::AppendBytes, COMDAT
; _this$ = ecx

; 28   : 	{	if (RealSize<size+sz) // надо добавить новый блок

	push	ebp
	mov	ebp, esp
	sub	esp, 244				; 000000f4H
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-244]
	mov	ecx, 61					; 0000003dH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+8]
	add	ecx, DWORD PTR _sz$[ebp]
	mov	edx, DWORD PTR _this$[ebp]
	cmp	DWORD PTR [edx+12], ecx
	jae	$LN2@AppendByte

; 29   : 		{
; 30   : 			RealSize = ((size+sz)/BlockSize+((size+sz)%BlockSize==0?0:1))*BlockSize;

	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+8]
	add	eax, DWORD PTR _sz$[ebp]
	xor	edx, edx
	mov	ecx, 512				; 00000200H
	div	ecx
	test	edx, edx
	jne	SHORT $LN4@AppendByte
	mov	DWORD PTR tv76[ebp], 0
	jmp	SHORT $LN5@AppendByte
$LN4@AppendByte:
	mov	DWORD PTR tv76[ebp], 1
$LN5@AppendByte:
	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [edx+8]
	add	eax, DWORD PTR _sz$[ebp]
	shr	eax, 9
	add	eax, DWORD PTR tv76[ebp]
	shl	eax, 9
	mov	ecx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [ecx+12], eax

; 31   : 			char *OldData = data; data = 0;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+4]
	mov	DWORD PTR _OldData$3[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax+4], 0

; 32   : 			data = new char[RealSize];

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+12]
	push	ecx
	call	??_U@YAPAXI@Z				; operator new[]
	add	esp, 4
	mov	DWORD PTR $T2[ebp], eax
	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR $T2[ebp]
	mov	DWORD PTR [edx+4], eax

; 33   : 			memcpy(data, OldData, size);

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+8]
	push	ecx
	mov	edx, DWORD PTR _OldData$3[ebp]
	push	edx
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+4]
	push	ecx
	call	_memcpy
	add	esp, 12					; 0000000cH

; 34   : 			delete[] OldData;

	mov	eax, DWORD PTR _OldData$3[ebp]
	mov	DWORD PTR $T1[ebp], eax
	mov	ecx, DWORD PTR $T1[ebp]
	push	ecx
	call	??_V@YAXPAX@Z				; operator delete[]
	add	esp, 4
$LN2@AppendByte:

; 35   : 		};
; 36   : 		memcpy(&data[size], mem, sz);

	mov	eax, DWORD PTR _sz$[ebp]
	push	eax
	mov	ecx, DWORD PTR _mem$[ebp]
	push	ecx
	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [edx+4]
	mov	ecx, DWORD PTR _this$[ebp]
	add	eax, DWORD PTR [ecx+8]
	push	eax
	call	_memcpy
	add	esp, 12					; 0000000cH

; 37   : 		size += sz; };

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+8]
	add	ecx, DWORD PTR _sz$[ebp]
	mov	edx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [edx+8], ecx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 244				; 000000f4H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	8
?AppendBytes@?$__TBD_TMemory@$0CAA@@@IAEXPAXI@Z ENDP	; __TBD_TMemory<512>::AppendBytes
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.h
;	COMDAT ?SetSize@?$__TBD_TMemory@$0CAA@@@IAEXI@Z
_TEXT	SEGMENT
$T1 = -224						; size = 4
$T2 = -212						; size = 4
_this$ = -8						; size = 4
_k$ = 8							; size = 4
?SetSize@?$__TBD_TMemory@$0CAA@@@IAEXI@Z PROC		; __TBD_TMemory<512>::SetSize, COMDAT
; _this$ = ecx

; 23   : 	{	delete[] data;

	push	ebp
	mov	ebp, esp
	sub	esp, 228				; 000000e4H
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-228]
	mov	ecx, 57					; 00000039H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+4]
	mov	DWORD PTR $T2[ebp], ecx
	mov	edx, DWORD PTR $T2[ebp]
	push	edx
	call	??_V@YAXPAX@Z				; operator delete[]
	add	esp, 4

; 24   : 		data = new char[k];

	mov	eax, DWORD PTR _k$[ebp]
	push	eax
	call	??_U@YAPAXI@Z				; operator new[]
	add	esp, 4
	mov	DWORD PTR $T1[ebp], eax
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR $T1[ebp]
	mov	DWORD PTR [ecx+4], edx

; 25   : 		size = k; RealSize = k;	};

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR _k$[ebp]
	mov	DWORD PTR [eax+8], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR _k$[ebp]
	mov	DWORD PTR [eax+12], ecx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 228				; 000000e4H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
?SetSize@?$__TBD_TMemory@$0CAA@@@IAEXI@Z ENDP		; __TBD_TMemory<512>::SetSize
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.h
;	COMDAT ?Reset@?$__TBD_TMemory@$0CAA@@@IAEXXZ
_TEXT	SEGMENT
$T1 = -212						; size = 4
_this$ = -8						; size = 4
?Reset@?$__TBD_TMemory@$0CAA@@@IAEXXZ PROC		; __TBD_TMemory<512>::Reset, COMDAT
; _this$ = ecx

; 20   : 	{	delete[] data; data = 0; size = 0; RealSize = 0; };

	push	ebp
	mov	ebp, esp
	sub	esp, 216				; 000000d8H
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-216]
	mov	ecx, 54					; 00000036H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+4]
	mov	DWORD PTR $T1[ebp], ecx
	mov	edx, DWORD PTR $T1[ebp]
	push	edx
	call	??_V@YAXPAX@Z				; operator delete[]
	add	esp, 4
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax+4], 0
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax+8], 0
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax+12], 0
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 216				; 000000d8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?Reset@?$__TBD_TMemory@$0CAA@@@IAEXXZ ENDP		; __TBD_TMemory<512>::Reset
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.h
;	COMDAT ??1?$__TBD_TMemory@$0CAA@@@MAE@XZ
_TEXT	SEGMENT
$T1 = -212						; size = 4
_this$ = -8						; size = 4
??1?$__TBD_TMemory@$0CAA@@@MAE@XZ PROC			; __TBD_TMemory<512>::~__TBD_TMemory<512>, COMDAT
; _this$ = ecx

; 17   : 	 virtual ~__TBD_TMemory() { delete[] data; };

	push	ebp
	mov	ebp, esp
	sub	esp, 216				; 000000d8H
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-216]
	mov	ecx, 54					; 00000036H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], OFFSET ??_7?$__TBD_TMemory@$0CAA@@@6B@
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+4]
	mov	DWORD PTR $T1[ebp], ecx
	mov	edx, DWORD PTR $T1[ebp]
	push	edx
	call	??_V@YAXPAX@Z				; operator delete[]
	add	esp, 4
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 216				; 000000d8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
??1?$__TBD_TMemory@$0CAA@@@MAE@XZ ENDP			; __TBD_TMemory<512>::~__TBD_TMemory<512>
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.h
;	COMDAT ??0?$__TBD_TMemory@$0CAA@@@IAE@XZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
??0?$__TBD_TMemory@$0CAA@@@IAE@XZ PROC			; __TBD_TMemory<512>::__TBD_TMemory<512>, COMDAT
; _this$ = ecx

; 16   : 	 __TBD_TMemory() { data = 0; size = 0; RealSize = 0; };

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], OFFSET ??_7?$__TBD_TMemory@$0CAA@@@6B@
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax+4], 0
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax+8], 0
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax+12], 0
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
??0?$__TBD_TMemory@$0CAA@@@IAE@XZ ENDP			; __TBD_TMemory<512>::__TBD_TMemory<512>
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ?__empty_global_delete@@YAXPAXI@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
___formal$ = 12						; size = 4
?__empty_global_delete@@YAXPAXI@Z PROC			; __empty_global_delete, COMDAT

	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?__empty_global_delete@@YAXPAXI@Z ENDP			; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\smith\projects\callcenter\tbinarydata.cpp
;	COMDAT ?__empty_global_delete@@YAXPAX@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
?__empty_global_delete@@YAXPAX@Z PROC			; __empty_global_delete, COMDAT

	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?__empty_global_delete@@YAXPAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
